### ISSUE TITLE
Failed to download file from Generic File Storage on PR trigger; Missing required input: source

### ISSUE THREAD

**Issue by Tyler-Lopez** [bitrise-steplib/steps-file-downloader#11]
### Troubleshooting

- **[X]** I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? **File Downloader 1.1.0**
- Is the issue reproducible with the latest version? **YES**
- Does the issue happen sporadically, or every time? SPORADIC / **EVERY TIME**
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / **NOT APPLICABLE**

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

As reported in the closed-without-successful outcome issue ticket here: https://github.com/bitrise-steplib/steps-file-downloader/issues/6

I am experiencing the same issue. On a public app, I am receiving the "Missing required input: source", whenever I attempt to use File Downloader as a step in a PR trigger, which is necessary.

### Bitrise info

- Build URL: _Please share the build URL with us.
https://app.bitrise.io/build/9143b626-6790-4627-b7de-3ef0b1664d32

- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

```
Configs:
  * source: 
  * destination: ./app/google-services.json
  * file_permission 
[!] Missing required input: source
```

### Steps to reproduce

1. Create PR trigger.
2. Use File Downloader as a step and set  the source as an environment variable from Generic File Storage.
3. Watch it fail.

**Comment by a-honcharov-it** [comment]
Have the same issue, it seems environment variables aren't replaced.
