### ISSUE TITLE
Failed to download file from Generic File Storage on PR trigger even when expose for pull request is enabled

### ISSUE THREAD

**Issue by mark-veenstra** [bitrise-steplib/steps-file-downloader#6]
Hi,

I enabled the option Expose for Pull Rquest in the UI:
![image](https://user-images.githubusercontent.com/8984015/82412497-0ccf0880-9a74-11ea-88d1-23a2817fec2a.png)

But when I use it on a build triggered by a PR change it fails to download the file:
```
+------------------------------------------------------------------------------+

| (5) file-downloader@1                                                        |
+------------------------------------------------------------------------------+
| id: file-downloader                                                          |
| version: 1.0.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2020-05-19T15:14:09Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
  * source: 
  * destination: example/ios/Runner/GoogleService-Info.plist
[!] Missing required input: source
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | file-downloader@1 (exit code: 1)                              | 2.52 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...://github.com/bitrise-steplib/steps-file-downloader/issues |
| Source: https://github.com/bitrise-steplib/steps-file-downloader             |
+---+---------------------------------------------------------------+----------+
```

It does work on push triggers which I tested first, but on PR changes it does not. Also tried to use the Generic File Storage downloader, but also in that case the files are not there, see https://github.com/bitrise-steplib/steps-script/issues/18.

See next output log: https://app.bitrise.io/build/398de847efd9b5b6#?tab=log

**Comment by Roland-Bak** [comment]
Hi there Mark! 👋
Can you let us know if your app is set to Public?
It is a know issue that  Workflow editor shows the EXPOSE FOR PULL REQUESTS switch for Public apps, even if Bitrise intentionally dot not exposes GENERIC FILE STORAGE objects for Public app builds.
We are working on fixing this, because of the confusion and frustration it can bring, sorry for the inconvenience!

**Comment by mark-veenstra** [comment]
Yes our app is set to public since it is an opensource Flutter plugin we are building. The example app is something we would like to build automatically.

Therefore it is set to Public and also therefore the switch `EXPOSE FOR PULL REQUESTS` is also set to `ON`. Also I set the switch for `Enable manual build approval option` to `ON`:
![image](https://user-images.githubusercontent.com/8984015/84377308-b2dce100-abe2-11ea-8880-e9bd5278b2da.png)

I would expect that when a build is triggered by a fork we can first approve the code and it the code does not try to steal credentials we can manually trigger the build. This is exactly what we would like to have so we can have automatic builds for submitted PRs from forks. And also keep it safe.

So therefore we would need all of those features.
